   
name: 'build-docker-image'

runs:
  using: "composite"
  steps:
    - name: Build the Docker image
      run:  |
         docker build --no-cache -t ${{ ENV.REGISTRY_URL }}/${{ ENV.REGISTRY_REPOSITORY }}/${{ ENV.REGISTRY_REPOS_TAG_NAME }}:$REGISTRY_REPOS_TAG_VERSION -f Dockerfile .
         echo 'Build docker image succeeded.'
         echo 'The information of docker image by below:'
         docker image ls -f reference="${{ ENV.REGISTRY_URL }}/${{ ENV.REGISTRY_REPOSITORY }}/${{ ENV.REGISTRY_REPOS_TAG_NAME }}:$REGISTRY_REPOS_TAG_VERSION"
         echo 'Next step will push docker image to jfrog artifactory.'
         echo 'artifactory_registry_repos_tag_version == $REGISTRY_REPOS_TAG_VERSION'
      shell: bash
      
    - name: Clean up old code
      run:  rm -r ${{ ENV.ACTIONS_RUNNER_FOLDER }}/_work/ODC-GithubAction/ODC-GithubAction/target/helloWorld-0.0.1-SNAPSHOT.jar
      shell: bash
