# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
name: build-source-code
env:
  BUILD_JAR: helloWorld-0.0.1-SNAPSHOT.jar

on:
  workflow_dispatch:

jobs:
  build-source-code-job:

    runs-on: self-hosted
    steps:
    - name: Clean up old code
      run:  rm -rf ${{ github.workspace }}/*
      
    - uses: actions/checkout@v2
    #- name: Set up JDK 8
    #  uses: actions/setup-java@v2
    #  with:
    #    java-version: '8'
        
    #- name: Build with Maven
      #run: mvn clean package -Dmaven.test.skip=true
    
    - name: Publish to JFrog Artifactory
      run: mvn deploy
        
    - name: Build source code result
      run: |
        echo 'Build source code succeeded.'
        echo 'The jar address of build is ${{ github.workspace }}/target/${{ env.BUILD_JAR }}'.
        echo 'The jar is deployed to JFrog Artifactory.The adderss is http://artifactrepo-dev:8082/artifactory/int_docker_dev/projects/idf/com/study/helloWorld/0.0.1-SNAPSHOT.'
        echo 'Next step will build docker image.'
