# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
name: build-source-code


#env:
#  HELLOWORLD_JAR_NAME: helloWorld
#  HELLOWORLD_JAR_VERSION: 0.0.1-SNAPSHOT
#  HELLOWORLD_JAR_ADDERSS: http://artifactrepo-dev:8082/artifactory/int_maven_dev/com/study
#  RUNNER_REPOSITORY: /appl/idf/script/ODC/repository

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-source-code-job:

#    runs-on: [ self-hosted ]
    runs-on: ubuntu-latest
    
    steps:
    - name: load env
      id: loadenv
      uses: ./.github/actions/env
      
#     - name: Clean up old code
#       run:  rm -rf ${{ github.workspace }}/*
      
    - uses: actions/checkout@v2
    #- name: Set up JDK 8
    #  uses: actions/setup-java@v2
    #  with:
    #    java-version: '8'
    
    #- name: Build with Maven
      #run: mvn clean package -Dmaven.test.skip=true
      
#    - name: delete runner server local maven repository 
#      run: rm -rf ${{ steps.loadenv.outputs.RUNNER_REPOSITORY }}/*

#    测试变量，先注释      
#    - name: Publish to JFrog Artifactory
#      run: mvn deploy -s settings.xml
        
    - name: Build source code result
      run: |
        echo 'Build source code succeeded.'
        echo 'The jar address of build is ${{ github.workspace }}/target/${{ steps.loadenv.outputs.HELLOWORLD_JAR_NAME }}-${{ steps.loadenv.outputs.HELLOWORLD_JAR_VERSION }}.jar'.
        echo 'The jar is deployed to JFrog Artifactory.The adderss is ${{ steps.loadenv.outputs.HELLOWORLD_JAR_ADDERSS }}/${{ steps.loadenv.outputs.HELLOWORLD_JAR_NAME }}/${{ steps.loadenv.outputs.HELLOWORLD_JAR_VERSION }}.'
        echo 'Next step will build docker image.'
    
    - name: variable 
        run: |
          echo 'build source code 使用到的变量'
          echo 'github.workspace  -------------->  ${{ github.workspace }}'
          echo 'steps.loadenv.outputs.RUNNER_REPOSITORY  -------------->  ${{ steps.loadenv.outputs.RUNNER_REPOSITORY }}'
          echo 'steps.loadenv.outputs.HELLOWORLD_JAR_NAME  -------------->  ${{ steps.loadenv.outputs.HELLOWORLD_JAR_NAME }}'
          echo 'steps.loadenv.outputs.HELLOWORLD_JAR_VERSION  -------------->  ${{ steps.loadenv.outputs.HELLOWORLD_JAR_VERSION }}'
          echo 'steps.loadenv.outputs.HELLOWORLD_JAR_ADDERSS  -------------->  ${{ steps.loadenv.outputs.HELLOWORLD_JAR_ADDERSS }}'
