on:
  workflow_dispatch:

jobs:

  hello_world_job:

    runs-on: ubuntu-latest

    steps:

      # Use the output from the `hello` step
      - name: outputs value
        id: odc
        run: echo "The time was ${{ steps.fuck.outputs.time }}"
