name: push-image-artifactory
on:
  workflow_dispatch:
    inputs:
      REGISTRY_REPOSITORY:
        required: true
        type: string
      REGISTRY_REPOS_TAG_NAME:
        required: true
        type: string
      REGISTRY_REPOS_TAG_VERSION:
        required: true
        type: string
        
  workflow_call:
    inputs:
      REGISTRY_REPOSITORY:
        required: true
        type: string
      REGISTRY_REPOS_TAG_NAME:
        required: true
        type: string
      REGISTRY_REPOS_TAG_VERSION:
        required: true
        type: string
      
jobs:
  push-image-artifactory-job:
    runs-on: [ self-hosted ]
    steps:
    
    - name: load env
      id: loadenv
      uses: ./.github/actions/env
    
    - name: Docker login JFrog Artifactory
      run:  |
        sudo docker login https://${{ secrets.REGISTRY_URL }}
        echo 'Login jfrog artifactory succeeded.'
      
    - name: Push to JFrog Artifactory
      run:  |
        sudo docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_REPOSITORY }}/${{ secrets.REGISTRY_REPOS_TAG_NAME }}:${{ secrets.REGISTRY_REPOS_TAG_VERSION }}
        echo 'Push docker image to jfrog artifactory succeeded.'
        echo 'The address of jfrog artifactory image is: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_REPOSITORY }}/${{ secrets.REGISTRY_REPOS_TAG_NAME }}'
        echo 'Next step will deploy jfrog artifactory image to openshift'

      
    - name: Remove Docker temp image
      run:  |
        sudo docker rmi ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_REPOSITORY }}/${{ secrets.REGISTRY_REPOS_TAG_NAME }}:${{ secrets.REGISTRY_REPOS_TAG_VERSION }}  
        echo 'Remove docker temp image succeeded.'
        
    - name: laod env
      run:  |
        echo 'REGISTRY_URL----------------${{ steps.loadenv.outputs.REGISTRY_URL }}'
        echo 'REGISTRY_REPOSITORY----------------${{ github.event.inputs.REGISTRY_REPOSITORY }}'
        echo 'REGISTRY_REPOS_TAG_NAME----------------${{ github.event.inputs.REGISTRY_REPOS_TAG_NAME }}'
        echo 'REGISTRY_REPOS_TAG_VERSION----------------${{ github.event.inputs.REGISTRY_REPOS_TAG_VERSION }}'


